[package]
name = "ai-dag-planner"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "DAG planning orchestration"
repository = "https://github.com/VirendraChavda/rust"
readme = "README.md"
keywords = ["ai", "backend", "rust"]
categories = ["development-tools"]

[dependencies]
ai-graph-core = { path = "../ai-graph-core" }
