[package]
name = "ai-dag-resource-scheduler"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Resource-aware DAG scheduling"
repository = "https://github.com/VirendraChavda/rust"
readme = "README.md"
keywords = ["ai", "backend", "rust"]
categories = ["development-tools"]

[dependencies]